# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - red
          - green
          - dev
          - qa
          - uat
          - prod
  
jobs:
  deploy-dev:
    if: inputs.environment == 'dev' || inputs.environment == 'red' || inputs.environment == 'green'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ vars.NAMESPACE }} is the environment
      - name: Run a one-line script2
        run: echo ${{ github.event.inputs.environment }} is the environment
  deploy-qa:
      if: inputs.environment == 'qa'
      runs-on: ubuntu-latest
      environment: qa
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
  
        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo ${{ vars.NAMESPACE }} is the environment
        - name: Run a one-line script2
          run: echo ${{ github.event.inputs.environment }} is the environment
          
